version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://postgres:homuhomu@postgres:5432/?sslmode=disable
      REDIS_URL: redis:6379

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: homuhomu
      POSTGRES_USER: postgres
    ports:
      - "5435:5432"
    volumes:
      - ./app/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: on-failure:3

  redis:
    image: redis:latest
    command: redis-server
    volumes:
      - redis:/var/lib/redis
      - redis-config:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"

volumes:
  redis:
  redis-config: